### ISSUE TITLE
Naut Coin Mac Wallet 1.2 won't sync

### ISSUE THREAD

**Issue by volcanicc** [nautiluscoin/nautiluscoin#8]
Hi guys

Tried the website to get support which doesn't appear to have any contact, so  then I googled and found the reddit threads.

Still no luck so far even after I tried the terminal trick shown in the reddit thread here http://www.reddit.com/r/nautiluscoin/comments/2j188k/mac_wallet_wont_sync/

I was running 1.1 so I updated to v1.2, balance showing correctly, but still will not sync.

Mac OSX 10.8.5.

Cheers
DG

**Comment by jyap808** [comment]
Works fine and is syncing. Closing issue.
